version: 2.0

jobs:
  test:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - run:
          name: Install
          command: yarn
      - run:
          name: Test
          command: yarn test
  release:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - run:
          name: Release
          command: npx semantic-release@15

workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only: master
